OPENAI_CHAT_COMPLETIONS = 'openai_chat_completions'
OPENAI_RESPONSES = 'openai_responses'
ANTHROPIC_MESSAGES = 'anthropic_messages'
GEMINI_GENERATE_CONTENT = 'gemini_generate_content'
OPENROUTER_CHAT = 'openrouter_chat'
OPENROUTER_RESPONSES = 'openrouter_responses'
XAI_CHAT = 'xai_chat'
XAI_RESPONSES = 'xai_responses'

KNOWN_PROTOCOLS = frozenset(
    {
        OPENAI_CHAT_COMPLETIONS,
        OPENAI_RESPONSES,
        ANTHROPIC_MESSAGES,
        GEMINI_GENERATE_CONTENT,
        OPENROUTER_CHAT,
        OPENROUTER_RESPONSES,
        XAI_CHAT,
        XAI_RESPONSES,
    }
)

NATIVE_PROTOCOLS = frozenset({ANTHROPIC_MESSAGES, GEMINI_GENERATE_CONTENT})
RESPONSES_PROTOCOLS = frozenset({OPENAI_RESPONSES, OPENROUTER_RESPONSES, XAI_RESPONSES})
OPENAI_CHAT_COMPATIBLE_PROTOCOLS = frozenset(
    {OPENAI_CHAT_COMPLETIONS, OPENROUTER_CHAT, XAI_CHAT}
)
